import = [
  "/usr/lib/node_modules/alacritty-themes/themes/Catppuccin-Mocha.toml"
]

[env]
TERM = "alacritty"

[font]
size = 12
builtin_box_drawing = true

  [font.bold]
  family = "Mononoki Nerd Font"
  style = "Bold"

  [font.bold_italic]
  family = "Mononoki Nerd Font"
  style = "Bold Italic"

  [font.italic]
  family = "Mononoki Nerd Font"
  style = "Italic"

  [font.normal]
  family = "Mononoki Nerd Font"
  style = "Regular"

  [font.offset]
  x = 0
  y = 0

  [font.glyph_offset]
  x = 0
  y = 0

[scrolling]
history = 50_000

[window]
opacity = 0.8
startup_mode = "Maximized"
title = "Alacritty"

  [window.class]
  general = "Alacritty"
  instance = "Alacritty"

  [window.padding]
  x = 5
  y = 5
