import = ["/home/sam_tunder/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[env]
TERM = "alacritty"

[font]
size = 11.0

[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Mononoki Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Mononoki Nerd Font"
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 1

[scrolling]
history = 50000

[window]
opacity = 0.8
startup_mode = "Maximized"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5
